ongr_translations_list_page:
    path: /
    methods: [GET]
    defaults:
        _controller: ONGRTranslationsBundle:List:index

ongr_translations_list_get_initial_data:
    path: /initial-data
    methods: [GET]
    defaults:
        _controller: ONGRTranslationsBundle:List:getInitialData
    options:
        expose: true

ongr_translations_list_get_translations:
    path: /list/translations
    methods: [GET]
    defaults:
        _controller: ONGRTranslationsBundle:List:list
    options:
        expose: true

ongr_translations_api_update:
    path: /_api/{id}
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:update
    options:
        expose: true

ongr_translations_api_get:
    path: /_api/{id}
    methods: [GET]
    defaults:
        _controller: ONGRTranslationsBundle:Api:get
    options:
        expose: true

ongr_translations_api_export:
    path: /_api/export
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:export
    options:
        expose: true

ongr_translations_api_history:
    path: /_api/history/{id}
    methods: [GET]
    defaults:
        _controller: ONGRTranslationsBundle:Api:history
    options:
        expose: true
